spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}?useUnicode=true&characterEncoding=utf-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379