spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 112107190288-0bfq826ct3gghhv5ttbo5mvgv3vcungi.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
          naver:
            client-id: q_Am850BkUjNQ2BoSJ6O
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          #          facebook:
          #            client-id: 페이스북 클라이언트 ID
          #            client-secret: 페이스북 암호키
          #            scope:
          #              - public_profile
          kakao:
            authorization-grant-type: authorization_code
            client-id: cb7b834c397dc01ed62670b9633cb2dc
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: client_secret_post
            client-name: Kakao
          github:
            client-id: a0e9ff66f527cc1e06b6
            client-secret: ${GITHUB_CLIENT_SECRET}
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id