spring:
  config:
    import:
      - classpath:env.yml
  profiles:
    active: oauth,db
jwt:
  secret: ${JWT_SECRET}
  url: "http://py:5000/jwt/"
  issue: "issue"
  logout: "logout"
  reissue: "reissue"
