spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import:
      - classpath:env.yml
  profiles:
    active: oauth,db
jwt:
  secret: ${JWT_SECRET}
  url: "http://py:5000/jwt/"
  issue: "issue"
  logout: "logout"
  reissue: "reissue"
