spring:
  config:
    import:
      - classpath:env.yml
  profiles:
    active: oauth,db
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  #    refresh: ${JWT_REFRESH}
  issuer: ${JWT_ISSUER}
